import type { Metadata } from "next";
import { DM_Sans } from 'next/font/google';
import "./globals.css";

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['300', '700'], 
  variable: '--font-dm-sans', 
});

export const metadata: Metadata = {
  title: "Portifolio Lua",
  description: "Generated by Lua next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
